services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
  ollama:
    build:
      context: ./ollama
    networks:
      - default
  ai-service:
    build:
      context: ./ai-service
    environment:
      - OLLAMA_URL=http://ollama:11434
      - GATEWAY_URL=http://gateway:8080
    networks:
      - default
  frontend:
    build:
      context: ./frontend
    ports:
      - "4173:4173"
    networks:
      - default

  auth-service:
    build:
      context: ./auth-service
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - default

  chat-service:
    build:
      context: ./chat-service
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - GATEWAY_URL=http://gateway:8080
    networks:
      - default

  gateway:
    build:
      context: ./gateway
    environment:
      - CHAT_SERVICE_URL=http://chat-service:8080
      - AUTH_SERVICE_URL=http://auth-service:8080
      - MONGO_URI=mongodb://mongo:27017
      - AI_SERVICE_URL=http://ai-service:8080
      - MEDIA_SERVICE_URL=http://media-service:8080
    ports:
      - "4242:4242"
    networks:
      - default

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - default

  media-service:
    depends_on:
      - minio
    build:
      context: ./media-service
    environment:
      - MINIO_URL=minio:9000
      - GATEWAY_URL=http://gateway:8080
      - ACCESS_KEY_ID=access-key-id
      - SECRET_ACCESS_KEY=secret-access-key
    networks:
      - default

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: access-key-id
      MINIO_ROOT_PASSWORD: secret-access-key
    networks:
      - default
    command: server /data --console-address ":9001"

networks:
  default:
    driver: bridge
