apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: ai-service
  name: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ai-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: ai-service
    spec:
      containers:
        - name: ai-service
          image: team6-managing.mni.thm.de/commz/ai-service:ecfbcfb9e677c1c51423d726feff6f71661bd90d
          env:
            - name: ENABLE_SWAGGER
              value: "true"
            - name: OLLAMA_URL
              value: http://ollama.default.svc.cluster.local:11434
            - name: GATEWAY_URL
              value: http://gateway.default.svc.cluster.local:8080
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
