definitions:
  utils.ServiceError:
    properties:
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is the API for the Media service
  title: Media Service API
  version: "1.0"
paths:
  /:
    post:
      consumes:
      - image/jpeg
      description: Upload a image
      parameters:
      - description: Authenticated user JWT token
        in: header
        name: commz-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Message Updated
          schema:
            type: string
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/utils.ServiceError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ServiceError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ServiceError'
      security:
      - ApiKeyAuth: []
      summary: Upload a image
      tags:
      - images
  /{imageName}:
    get:
      consumes:
      - application/json
      description: Get a image by its Name
      parameters:
      - description: Name of the image
        in: path
        name: imageName
        required: true
        type: string
      produces:
      - image/jpeg
      responses:
        "200":
          description: Image
          schema:
            type: string
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/utils.ServiceError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ServiceError'
        "404":
          description: Image not found
          schema:
            $ref: '#/definitions/utils.ServiceError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ServiceError'
      summary: Get a image by imageName
      tags:
      - images
  /version:
    get:
      responses:
        "200":
          description: version
          schema:
            type: string
      summary: Get the service Version
swagger: "2.0"
