name: Test, Build and Deploy Production
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Docker image
        run: |
          docker login team6-managing.mni.thm.de:3000 -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --no-cache -t team6-managing.mni.thm.de:3000/commz/media-service:${{ gitea.sha }} . --push
  sonarqube:
    runs-on: ubuntu-latest
    container:
      image: sonarsource/sonar-scanner-cli:4
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Scan container
        run: |
          sonar-scanner -Dsonar.projectKey=devops-media-service -Dsonar.sources=. -Dsonar.host.url=https://scm.thm.de/sonar -Dsonar.login=$SONAR_PRIVATE_KEY
