apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: chat-service
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: chat-service
    spec:
      containers:
        - name: chat-service
          image: team6-managing.mni.thm.de/commz/chat-service:ecfbcfb9e677c1c51423d726feff6f71661bd90d
          env:
            - name: ENABLE_SWAGGER
              value: "true"
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
